config/routes.rb
MongoMetrics::Engine.routes.draw do
  root to: "metrics#index"
  resources :metrics, only: [:index, :destroy]
end

app/models/mongo_metrics/metric.rb
require "csv"

module MongoMetrics
  class Metric
    include Mongoid::Document

    field :name, type: String
    field :duration, type: Integer
    field :instrumenter_id, type: String
    field :payload, type: Hash
    field :started_at, type: DateTime
    field :created_at, type: DateTime

    def self.store!(args)
      metric = new
      metric.parse(args)
      metric.save!
    end

    def parse(args)
      self.name            = args[0]
      self.started_at      = args[1]
      self.duration        = (args[2] - args[1]) * 1000000
      self.instrumenter_id = args[3]
      self.payload         = args[4]
      self.created_at      = Time.now.utc
    end

    def to_csv
      [name, started_at, duration, instrumenter_id, created_at].to_csv
    end
  end
end

app/controllers/mongo_metrics/application_controller.rb
module MongoMetrics
  class ApplicationController < ActionController::Base
  end
end

app/controllers/mongo_metrics/metrics_controller.rb
module MongoMetrics
  class MetricsController < ApplicationController

    def index
      @metrics = Metric.all
      respond_to do |format|
        format.html
        format.json
        format.csv{ render csv: @metrics }
      end
    end

    def destroy
      @metric = Metric.find(params[:id])
      @metric.destroy
      redirect_to root_path
    end
  end
end

app/helpers/mongo_metrics/application_helper.rb
module MongoMetrics
  module ApplicationHelper
  end
end

app/views/layouts/mongo_metrics/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoMetrics</title>
  <%= stylesheet_link_tag    "mongo_metrics/application", media: "all" %>
  <%= javascript_include_tag "mongo_metrics/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mongo_metrics/metrics/index.html.erb
<h1>Listing Metrics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Duration</th>
    <th>Started At</th>
    <th>Payload</th>
    <th></th>
  </tr>

  <%= content_tag_for :tr, @metrics do |metric| %>
    <td><%= metric.name %></td>
    <td><%= metric.duration / 1000 %>ms</td>
    <td><%=  time_ago_in_words metric.started_at %> ago</td>
    <td>
      <ul>
        <% metric.payload.each do |k,v| %>
          <li><%= k.humanize %>: <%= v %></li>
        <% end %>
      </ul>
    </td>
    <td>
      <%= link_to 'Destroy', metric_path(metric),
      method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  <% end %>
</table>